import type { TeachingNote } from "./types";

/** Teaching notes for Statistics and Mechanics. */
export const appliedNotes: TeachingNote[] = [
  // ── Statistics ────────────────────────────────────────────────────────────
  {
    paper: "statistics",
    specCode: "1.1",
    idea: "You rarely measure a whole population, so you take a sample and hope it represents it. Each sampling method trades effort against bias, and the examinable skill is naming that trade-off rather than performing the sampling.",
    method: [
      "Simple random: everyone has an equal chance, usually via numbered names and random numbers.",
      "Systematic: take every $k$th item from a list after a random start.",
      "Stratified: split the population into groups and sample each in proportion to its size.",
      "Opportunity and quota: convenient, but not random, so conclusions are weaker.",
      "A census covers everyone — accurate but expensive, and impossible if testing destroys the item.",
    ],
    watchFor: [
      "Stratified sample sizes must be rounded sensibly and still total the required number.",
      "Systematic sampling goes wrong if the list has a repeating pattern matching the interval.",
      "Answers must be in context: name the population and the sampling units, not just the method.",
    ],
  },
  {
    paper: "statistics",
    specCode: "2.1",
    idea: "Each diagram answers a different question. Histograms show the shape of a distribution using AREA, box plots compare spread and skew at a glance, and cumulative frequency curves are for reading off medians and percentiles.",
    method: [
      "Histogram: frequency density is frequency divided by class width, and it is the AREA that represents frequency.",
      "Box plot: mark the minimum, lower quartile, median, upper quartile and maximum.",
      "Cumulative frequency: plot against the UPPER boundary of each class, then read percentiles off the vertical axis.",
      "Skew: if the mean exceeds the median the distribution is positively skewed, and the long tail is to the right.",
      "When comparing two distributions, comment on both average and spread, in context.",
    ],
    watchFor: [
      "Plotting frequency instead of frequency density on a histogram with unequal class widths.",
      "Plotting cumulative frequency against midpoints. It must be the upper boundary.",
      "Comparing only the averages. A comparison question wants spread too, and the marks are split.",
    ],
  },
  {
    paper: "statistics",
    specCode: "2.2",
    idea: "A regression line summarises a linear relationship between two variables, and correlation measures how tightly the points hug it. Neither says anything at all about cause.",
    method: [
      "Identify which variable is explanatory (the $x$) and which is the response.",
      "The line $y=a+bx$ predicts $y$ from $x$; it should not be used the other way round.",
      "Interpret the gradient in context: the change in $y$ for each unit increase in $x$.",
      "Predicting inside the range of the data is interpolation, and is reliable.",
      "Predicting outside it is extrapolation, and is not — the relationship has not been observed there.",
    ],
    watchFor: [
      "Claiming causation from correlation. A third variable may drive both.",
      "Extrapolating. Say so explicitly when a question hands you a value outside the data range — that is exactly what is being tested.",
      "Reading a strong correlation as proof that the relationship is linear beyond the data.",
    ],
  },
  {
    paper: "statistics",
    specCode: "2.3",
    idea: "Averages say where a distribution sits and measures of spread say how wide it is. Coding — rescaling the data before calculating — makes the arithmetic manageable and changes the results in a predictable way.",
    method: [
      "Mean is the total divided by the count; the median is the middle value once ordered; the mode is the most frequent.",
      "Standard deviation measures typical distance from the mean; variance is its square.",
      "For grouped data, use midpoints as representative values.",
      "Under the coding $y=\\dfrac{x-a}{b}$: the mean transforms the same way, but the standard deviation is divided by $b$ only.",
      "To undo coding, reverse it: $\\bar{x}=b\\bar{y}+a$ and $\\sigma_{x}=b\\sigma_{y}$.",
    ],
    watchFor: [
      "Adding a constant changes the mean but NOT the standard deviation — shifting data does not spread it.",
      "Forgetting to undo the coding at the end.",
      "Grouped data gives an ESTIMATE, because the original values are gone.",
    ],
  },
  {
    paper: "statistics",
    specCode: "2.4",
    idea: "An outlier is a value far enough from the rest to be worth questioning. There are standard rules for flagging one, but flagging is not the same as deleting: the value may be perfectly genuine.",
    method: [
      "Common rule: more than $1.5\\times$ the interquartile range beyond a quartile.",
      "Alternative rule: more than 2 standard deviations from the mean. The question will tell you which to use.",
      "Calculate the boundaries explicitly and compare each suspect value.",
      "State which values are outliers and which are not.",
      "Only remove a value if there is a reason to think it is an error.",
    ],
    watchFor: [
      "Using a rule the question did not specify.",
      "Deleting an outlier automatically. A genuine extreme value is data, not noise.",
      "Show the boundary calculation — it is where the method mark is.",
    ],
  },
  {
    paper: "statistics",
    specCode: "3.1",
    idea: "Mutually exclusive means two events cannot both happen. Independent means one happening does not change the chance of the other. They sound similar and are nearly opposites.",
    method: [
      "Mutually exclusive: $P(A\\cap B)=0$, so $P(A\\cup B)=P(A)+P(B)$.",
      "Independent: $P(A\\cap B)=P(A)\\times P(B)$.",
      "In general, $P(A\\cup B)=P(A)+P(B)-P(A\\cap B)$ — subtracting the overlap so it is not counted twice.",
      "Venn diagrams suit overlapping events; tree diagrams suit sequences of events.",
      "Fill in a Venn diagram from the middle outwards.",
    ],
    watchFor: [
      "Multiplying probabilities for events that are not independent. Without replacement, they never are.",
      "Treating independent events as mutually exclusive. If both can happen, $P(A\\cap B)$ is not zero.",
      "To PROVE independence, check that $P(A\\cap B)$ really equals $P(A)\\times P(B)$ — do not assume it.",
    ],
  },
  {
    paper: "statistics",
    specCode: "3.2",
    idea: "Conditional probability asks: given that one thing has happened, what is the chance of another? Knowing the first event has occurred shrinks the sample space, which is what changes the answer.",
    method: [
      "$P(A\\mid B)=\\dfrac{P(A\\cap B)}{P(B)}$ — the overlap divided by what you are now restricted to.",
      "On a tree diagram, the second set of branches already shows conditional probabilities.",
      "On a Venn diagram, restrict your attention to the given region and take the fraction of it.",
      "Rearranged: $P(A\\cap B)=P(A\\mid B)\\times P(B)$.",
      "If $A$ and $B$ are independent then $P(A\\mid B)=P(A)$: the condition tells you nothing.",
    ],
    watchFor: [
      "Getting the condition the wrong way round. $P(A\\mid B)$ and $P(B\\mid A)$ are usually different numbers.",
      "Dividing by the wrong total. The denominator is the probability of the thing you are given.",
      "Reading 'and' as 'given'. They are different questions.",
    ],
  },
  {
    paper: "statistics",
    specCode: "3.3",
    idea: "Choosing a probability model means assuming something about the situation. The examinable skill is naming those assumptions and judging whether the situation actually satisfies them.",
    method: [
      "Binomial needs: a fixed number of trials, two outcomes, a constant probability, and independence.",
      "Check each condition against the real situation one at a time.",
      "Name the specific condition that fails, and say why it fails.",
      "Suggest a refinement that would fix it.",
      "State the model formally, as $X\\sim B(n,p)$ or $X\\sim N(\\mu,\\sigma^{2})$.",
    ],
    watchFor: [
      "Criticising the model in general terms. 'It is unrealistic' earns nothing; naming the assumption earns the marks.",
      "Sampling without replacement breaks independence — a very common trap.",
      "Objecting to a condition the situation does not actually violate.",
    ],
  },
  {
    paper: "statistics",
    specCode: "4.1",
    idea: "A discrete random variable takes separate values, each with a probability, and those probabilities must total 1. The binomial is the standard case: counting successes in a fixed number of independent trials.",
    method: [
      "Check the four binomial conditions before using it.",
      "Write it as $X\\sim B(n,p)$.",
      "$P(X=r)=\\binom{n}{r}p^{r}(1-p)^{\\,n-r}$.",
      "Use the calculator's cumulative function for 'at most'; for 'at least', subtract from 1.",
      "For an unknown probability in a distribution table, use the fact that the probabilities sum to 1.",
    ],
    watchFor: [
      "Boundary errors. 'More than 5' is $1-P(X\\le5)$, while 'at least 5' is $1-P(X\\le4)$.",
      "Mixing up $n$ and $r$.",
      "$p$ must be the probability of the thing you are COUNTING.",
    ],
  },
  {
    paper: "statistics",
    specCode: "4.2",
    idea: "The normal distribution is the bell curve: continuous, symmetric about its mean, with almost everything within three standard deviations. Standardising converts any normal variable to the standard one, which is what makes a single table or function serve them all.",
    method: [
      "Write it as $X\\sim N(\\mu,\\sigma^{2})$ — the second parameter is the VARIANCE.",
      "Sketch the curve and shade the region you want. This prevents most errors.",
      "Standardise with $z=\\dfrac{x-\\mu}{\\sigma}$.",
      "Calculators give the area to the LEFT, so 'greater than' means subtracting from 1.",
      "To find $\\mu$ or $\\sigma$ from a given probability, work backwards from the $z$ value.",
    ],
    watchFor: [
      "Entering the variance where the calculator wants the standard deviation, or the reverse.",
      "Forgetting to subtract from 1 for an upper tail.",
      "By symmetry, a negative $z$ has the same tail area as its positive counterpart.",
    ],
  },
  {
    paper: "statistics",
    specCode: "4.3",
    idea: "Choosing between the binomial and the normal comes down to one question: are you counting separate things, or measuring something continuous?",
    method: [
      "Counting successes in a fixed number of trials: binomial.",
      "Measuring a continuous quantity that clusters symmetrically about an average: normal.",
      "Justify by reference to the conditions, not by the shape of the answer.",
      "A binomial with large $n$ and $p$ near $\\frac{1}{2}$ is roughly normal, but say so explicitly if you use that.",
      "State the parameters whichever you choose.",
    ],
    watchFor: [
      "Using the normal for something that can only take whole values, without saying it is an approximation.",
      "Using the binomial when the trials are not independent.",
      "The justification is the answer in these questions, not the arithmetic.",
    ],
  },
  {
    paper: "statistics",
    specCode: "5.1",
    idea: "A hypothesis test asks whether the evidence is strong enough to abandon a default assumption. The null hypothesis is that default; the significance level is how much surprise you demand before giving it up.",
    method: [
      "$H_{0}$ states the assumed value, always as an equality.",
      "$H_{1}$ states what you suspect: one-tailed with $<$ or $>$, two-tailed with $\\neq$.",
      "The significance level is the probability of rejecting a TRUE null hypothesis.",
      "For a two-tailed test, split the level between the two tails.",
      "Compare the probability of the observed result with the level, or compare the result with the critical region.",
    ],
    watchFor: [
      "Never 'accept' $H_{0}$ — you fail to reject it. Absence of evidence is not evidence of absence.",
      "Halving the significance level for a two-tailed test.",
      "The conclusion must be in context, mentioning the actual quantity rather than just $p$.",
    ],
  },
  {
    paper: "statistics",
    specCode: "5.2",
    idea: "For a binomial test you ask: if the null hypothesis were true, how likely is a result at least as extreme as the one I got? If that is smaller than the significance level, the evidence is strong enough.",
    method: [
      "State $H_{0}$ and $H_{1}$ in terms of $p$.",
      "Assume $H_{0}$ and write the distribution, $X\\sim B(n,p)$.",
      "Find the probability of a result AT LEAST as extreme as the observed one.",
      "Compare with the significance level, halved if two-tailed.",
      "Conclude in context, and say which hypothesis is rejected.",
    ],
    watchFor: [
      "Finding the probability of exactly the observed value instead of that value or more extreme.",
      "Getting the tail wrong. For $H_{1}: p>$, you want the upper tail.",
      "A critical region must be stated as a range of whole numbers, since the variable is discrete.",
    ],
  },
  {
    paper: "statistics",
    specCode: "5.3",
    idea: "Testing a mean uses the distribution of the SAMPLE mean, not of a single value. Averaging $n$ observations reduces the standard deviation by a factor of $\\sqrt{n}$, and that is the whole reason a sample is more informative than one measurement.",
    method: [
      "State $H_{0}: \\mu=\\ldots$ and $H_{1}$ with the appropriate direction.",
      "Under $H_{0}$, the sample mean is distributed $\\bar{X}\\sim N\\left(\\mu,\\dfrac{\\sigma^{2}}{n}\\right)$.",
      "So the standard deviation of $\\bar{X}$ is $\\dfrac{\\sigma}{\\sqrt{n}}$.",
      "Standardise: $z=\\dfrac{\\bar{x}-\\mu}{\\sigma/\\sqrt{n}}$.",
      "Compare with the critical value — 1.645 for a one-tailed test at 5%, 1.96 for two-tailed.",
    ],
    watchFor: [
      "Dividing by $\\sigma$ rather than $\\dfrac{\\sigma}{\\sqrt{n}}$. That tests a single observation, which is a different and much weaker question.",
      "Dividing by $n$ instead of $\\sqrt{n}$.",
      "The conclusion must be in context and must not claim proof.",
    ],
  },

  // ── Mechanics ─────────────────────────────────────────────────────────────
  {
    paper: "mechanics",
    specCode: "6.1",
    idea: "Mechanics is bookkeeping with units. Every quantity is either a scalar (size only) or a vector (size and direction), and keeping that straight prevents most of the errors in the whole paper.",
    method: [
      "Base units: metres, kilograms, seconds. Force is measured in newtons.",
      "Write units on every answer.",
      "Convert everything to base units before calculating — km/h to m/s, grams to kilograms.",
      "Scalars: distance, speed, mass, time. Vectors: displacement, velocity, acceleration, force.",
      "Check dimensions: an answer in newtons should come from a mass times an acceleration.",
    ],
    watchFor: [
      "Mixing units within one calculation. Grams and kilograms in the same line is the classic.",
      "Treating mass and weight as the same thing. Mass is in kilograms, weight is a force in newtons.",
      "Answers without units frequently lose the final mark.",
    ],
  },
  {
    paper: "mechanics",
    specCode: "7.1",
    idea: "Distance and displacement are different, and so are speed and velocity. The first of each pair ignores direction and can only grow; the second carries direction and can decrease or go negative.",
    method: [
      "Choose a positive direction and state it. Everything else follows from that choice.",
      "Displacement is measured from start to finish; distance counts every metre travelled.",
      "Velocity is the rate of change of displacement; speed is its magnitude.",
      "Acceleration is the rate of change of velocity — negative acceleration means slowing down only if moving in the positive direction.",
      "Speed and distance are never negative.",
    ],
    watchFor: [
      "Adding when the question wants a displacement, or subtracting when it wants a distance.",
      "Assuming negative acceleration always means slowing down. If velocity is also negative, it is speeding up.",
      "Not stating the positive direction, which makes every sign in the answer ambiguous.",
    ],
  },
  {
    paper: "mechanics",
    specCode: "7.2",
    idea: "A motion graph carries more than its line: on a displacement-time graph the GRADIENT is velocity, and on a velocity-time graph the AREA is displacement.",
    method: [
      "Displacement-time: gradient gives velocity, and a horizontal section means at rest.",
      "Velocity-time: gradient gives acceleration, area gives displacement.",
      "Split the area into triangles and rectangles and add them.",
      "Area below the axis counts as negative displacement.",
      "For distance travelled rather than displacement, add the magnitudes of the areas.",
    ],
    watchFor: [
      "Reading a velocity-time graph as if it showed position. A horizontal line there means constant velocity, not stationary.",
      "Ignoring the sign of an area below the axis.",
      "Area gives displacement, so for distance you must treat the negative parts as positive.",
    ],
  },
  {
    paper: "mechanics",
    specCode: "7.3",
    idea: "The suvat equations apply only when acceleration is CONSTANT. Each one omits a different variable, so the skill is listing what you know and picking the equation that misses the thing you do not care about.",
    method: [
      "List $s$, $u$, $v$, $a$, $t$ and mark which are known.",
      "You need three to find a fourth.",
      "Choose the equation that leaves out the variable you neither know nor want.",
      "Set a positive direction and keep every sign consistent with it.",
      "The formulae are in the booklet, so quoting them costs nothing.",
    ],
    watchFor: [
      "Using them when the acceleration is not constant. Then you need calculus instead.",
      "Sign errors on $g$: if upwards is positive, acceleration due to gravity is $-9.8$.",
      "'Released from rest' means $u=0$; 'comes to rest' means $v=0$.",
    ],
  },
  {
    paper: "mechanics",
    specCode: "7.4",
    idea: "When acceleration varies, suvat is useless and calculus takes over. Differentiating moves you from displacement to velocity to acceleration; integrating moves back the other way.",
    method: [
      "Differentiate displacement to get velocity, and again for acceleration.",
      "Integrate acceleration for velocity, and again for displacement.",
      "Every integration introduces a constant — use a stated condition to find it.",
      "At rest means $v=0$; maximum velocity means $a=0$.",
      "For distance travelled, check whether the velocity changes sign within the interval and split the integral if it does.",
    ],
    watchFor: [
      "Reaching for suvat when the acceleration is a function of time. If $a$ contains $t$, suvat does not apply.",
      "Losing the constant of integration.",
      "Integrating across a change of direction gives displacement, not distance travelled.",
    ],
  },
  {
    paper: "mechanics",
    specCode: "7.5",
    idea: "A projectile's horizontal and vertical motions are completely independent. Horizontally there is no acceleration; vertically it is $g$ downwards. Time is the only thing the two share.",
    method: [
      "Resolve the initial velocity into horizontal and vertical components.",
      "Horizontally: constant velocity, so distance is speed times time.",
      "Vertically: suvat with $a=-g$ if upwards is positive.",
      "At maximum height the VERTICAL velocity is zero — the horizontal component is unchanged.",
      "Use the time of flight from the vertical motion to get the horizontal range.",
    ],
    watchFor: [
      "Applying $g$ to the horizontal motion. There is no horizontal acceleration in this model.",
      "Thinking the speed is zero at the top. Only the vertical component is.",
      "Air resistance is ignored throughout, which is a modelling assumption worth stating if asked.",
    ],
  },
  {
    paper: "mechanics",
    specCode: "8.1",
    idea: "A force is a push or a pull. Newton's first law says that with no resultant force, a body stays at rest or keeps moving at constant velocity — motion itself needs no force, only a CHANGE of motion does.",
    method: [
      "Draw a force diagram and label every force before calculating anything.",
      "Weight always acts vertically downwards.",
      "A normal reaction acts perpendicular to the surface.",
      "A string can only pull, which is tension; a rod can also push, which is thrust.",
      "At rest or at constant velocity, the forces balance in every direction.",
    ],
    watchFor: [
      "Assuming movement implies a resultant force. Constant velocity means the forces are balanced.",
      "Using the right name: weight, normal reaction, tension, thrust, friction, resistance. Mark schemes do not accept 'the force of the table'.",
      "Forgetting a force entirely — the diagram is what prevents this.",
    ],
  },
  {
    paper: "mechanics",
    specCode: "8.2",
    idea: "Newton's second law, $F=ma$, connects the resultant force to the acceleration it produces. It is the resultant that matters, so the first job is always to combine the forces.",
    method: [
      "Draw the force diagram.",
      "Choose a positive direction, usually the direction of motion.",
      "Find the resultant force in that direction, as a sum with signs.",
      "Apply $F=ma$ using that resultant — never a single force on its own.",
      "Watch the units: newtons, kilograms, metres per second squared.",
    ],
    watchFor: [
      "Using one force instead of the resultant.",
      "Mass must be in kilograms. A mass given in grams needs converting first.",
      "If the acceleration comes out negative, the body is accelerating in the opposite direction to the one you chose — not necessarily slowing down.",
    ],
  },
  {
    paper: "mechanics",
    specCode: "8.3",
    idea: "Weight is the force gravity exerts on a mass: $W=mg$. Mass is a property of the object and never changes; weight depends on where it is, because $g$ varies with location.",
    method: [
      "$W=mg$, with mass in kilograms and $W$ in newtons.",
      "Use $g=9.8\\ \\mathrm{m\\,s^{-2}}$ unless told otherwise.",
      "For free fall, apply suvat with $a=g$ downwards.",
      "'Released from rest' means $u=0$.",
      "Be consistent about which direction is positive.",
    ],
    watchFor: [
      "Giving the mass when asked for the weight. They differ by a factor of $g$ and have different units.",
      "The sign of $g$ depends on your chosen positive direction.",
      "$g$ is given to two significant figures, which limits the accuracy of anything built on it.",
    ],
  },
  {
    paper: "mechanics",
    specCode: "8.4",
    idea: "Newton's third law says forces come in equal and opposite pairs acting on DIFFERENT bodies. For connected particles this is what lets you treat the system as a whole, or each body separately, whichever is easier.",
    method: [
      "For the whole system, internal forces such as the tension cancel — useful for finding the acceleration.",
      "For one body alone, the tension appears and can be found.",
      "Draw a separate force diagram for each body.",
      "Apply $F=ma$ to each, with the same acceleration for connected particles.",
      "Solve the resulting simultaneous equations.",
    ],
    watchFor: [
      "Applying the third law to two forces on the SAME body. The pair always acts on different objects.",
      "The tension in a light inextensible string is the same throughout, including over a smooth pulley.",
      "Getting the direction of the acceleration wrong for one of the two bodies — over a pulley, one goes up as the other goes down.",
    ],
  },
  {
    paper: "mechanics",
    specCode: "8.5",
    idea: "When forces act at angles, resolve each into perpendicular components and treat the two directions independently. It is the same trick as projectiles: split the problem into two simpler ones.",
    method: [
      "Choose two perpendicular directions, usually horizontal and vertical, or along and perpendicular to a slope.",
      "Resolve each force: the component along the direction of the angle uses cosine, the perpendicular one uses sine.",
      "Sum the components in each direction separately.",
      "Apply $F=ma$ in each direction — for equilibrium, each sum is zero.",
      "Combine at the end if a resultant magnitude is wanted.",
    ],
    watchFor: [
      "Mixing up sine and cosine. Check which side of the angle you want: adjacent takes cosine.",
      "On a slope, resolving the weight needs $mg\\cos\\theta$ perpendicular and $mg\\sin\\theta$ down the slope.",
      "Forgetting that a rope pulling upwards at an angle reduces the normal reaction.",
    ],
  },
  {
    paper: "mechanics",
    specCode: "8.6",
    idea: "Friction opposes motion, or the tendency to move, and has a maximum value proportional to the normal reaction. Below that maximum it takes whatever value is needed to keep things still.",
    method: [
      "$F\\le\\mu R$, where $\\mu$ is the coefficient of friction.",
      "On the point of sliding, friction is at its maximum: $F=\\mu R$.",
      "Find $R$ by resolving perpendicular to the surface.",
      "Friction acts opposite to the direction of motion or attempted motion.",
      "'Smooth' means no friction at all.",
    ],
    watchFor: [
      "Using $F=\\mu R$ when the object is not sliding or on the point of sliding. Then friction is only as large as it needs to be.",
      "Assuming $R=mg$ when another force has a vertical component. Resolve properly.",
      "On a slope, $R=mg\\cos\\theta$, not $mg$.",
    ],
  },
  {
    paper: "mechanics",
    specCode: "9.1",
    idea: "A moment measures a force's turning effect: force times perpendicular distance from the pivot. A rigid body in equilibrium needs both zero resultant force and zero resultant moment.",
    method: [
      "Moment = force $\\times$ perpendicular distance from the pivot.",
      "Choose a sensible pivot — taking moments about an unknown force eliminates it.",
      "Set clockwise moments equal to anticlockwise moments.",
      "Also resolve vertically: the total upward force equals the total downward force.",
      "The weight of a uniform rod acts at its centre.",
    ],
    watchFor: [
      "Using the distance along the force rather than the perpendicular distance. At an angle, that means multiplying by a sine or cosine.",
      "Forgetting the rod's own weight.",
      "'On the point of tilting' means the reaction at the other support has become zero — that is what makes the problem solvable.",
    ],
  },
];
