import type { TeachingNote } from "./types";

/**
 * Teaching notes for the remaining Pure topics: coordinate geometry,
 * sequences and series, exponentials and logarithms, numerical methods
 * and vectors.
 */
export const pureRestNotes: TeachingNote[] = [
  {
    paper: "pure",
    specCode: "3.1",
    idea: "A straight line is fixed by a gradient and one point it passes through. Everything else in this spec point — parallel, perpendicular, intersections — follows from those two facts.",
    method: [
      "Gradient between two points: $m=\\dfrac{y_{2}-y_{1}}{x_{2}-x_{1}}$.",
      "Equation through a known point: $y-y_{1}=m(x-x_{1})$. This is more reliable than $y=mx+c$ because there is no $c$ to find.",
      "Parallel lines share a gradient.",
      "Perpendicular gradients multiply to $-1$, so one is the negative reciprocal of the other.",
      "To find where two lines meet, solve their equations simultaneously.",
    ],
    watchFor: [
      "Subtracting the coordinates in different orders top and bottom, which flips the sign of the gradient.",
      "A vertical line has no gradient at all; its equation is $x=k$.",
      "If the question wants the form $ax+by+c=0$ with integer coefficients, clear the fractions — the final mark is for the form.",
    ],
  },
  {
    paper: "pure",
    specCode: "3.2",
    idea: "A circle is the set of points a fixed distance from a centre, which is exactly what $(x-a)^{2}+(y-b)^{2}=r^{2}$ says. Its geometry gives you two facts worth remembering: a tangent is perpendicular to the radius at its point of contact, and the perpendicular from the centre bisects any chord.",
    method: [
      "Read the centre and radius off the completed-square form: centre $(a,\\,b)$, radius $r$.",
      "If given the expanded form, complete the square in $x$ and in $y$ to get there.",
      "For a tangent at a point: find the radius gradient, take its negative reciprocal, and use the point.",
      "To test whether a line meets a circle, substitute and look at the discriminant of the resulting quadratic.",
      "For the circle through three points, use the fact that the angle in a semicircle is a right angle, or find where two perpendicular bisectors meet.",
    ],
    watchFor: [
      "Reading the centre with the wrong signs. $(x-3)^{2}$ means the centre is at $+3$.",
      "Forgetting that the equation gives $r^{2}$, so the radius needs a square root.",
      "When completing the square, the constants you subtract must be taken off the other side too.",
    ],
  },
  {
    paper: "pure",
    specCode: "3.3",
    idea: "Parametric equations describe a curve by saying where you are at each value of a third variable. That lets you describe curves that are not functions of $x$ at all, and it carries information a Cartesian equation throws away — such as direction and timing.",
    method: [
      "To convert to Cartesian, eliminate the parameter: make $t$ the subject of the easier equation and substitute into the other.",
      "If both equations are trigonometric, use an identity instead — $\\sin^{2}+\\cos^{2}=1$ is the usual route.",
      "To find where the curve crosses an axis, set the relevant coordinate to zero and solve for the parameter first.",
      "State the domain of the Cartesian equation if the parameter was restricted — the curve may only be part of what the equation describes.",
    ],
    watchFor: [
      "Substituting back into the equation you just rearranged, which gives an identity and no information.",
      "Squaring a fraction and forgetting to square its denominator.",
      "Losing the restriction on the parameter. The parametric curve is often only an arc of the full Cartesian curve.",
    ],
  },
  {
    paper: "pure",
    specCode: "3.4",
    idea: "Parametric form suits anything where two quantities both depend on a third — usually time. Projectile motion is the classic example: the horizontal and vertical positions are independent, and the shared parameter ties them together.",
    method: [
      "Identify what the parameter represents physically, usually time in seconds.",
      "Read each equation separately — one gives horizontal position, the other vertical.",
      "To answer 'when', solve for the parameter; to answer 'where', substitute it in.",
      "For maximum height, find where the vertical rate of change is zero.",
      "Interpret in context, with units, and check the answer is physically sensible.",
    ],
    watchFor: [
      "Using the wrong equation for the quantity asked about.",
      "Forgetting that the parameter can be restricted physically — negative time usually has no meaning.",
      "Giving a bare number without units or context in what is an AO3 question.",
    ],
  },
  {
    paper: "pure",
    specCode: "4.1",
    idea: "The binomial expansion multiplies out $(a+b)^{n}$ without doing the multiplication. For a positive whole $n$ the expansion stops; for a fractional or negative $n$ it runs forever and only converges for a restricted range of $x$.",
    method: [
      "For positive integer $n$, use $\\binom{n}{r}a^{n-r}b^{r}$, and take the coefficients from Pascal's triangle or the calculator.",
      "To find one particular term, work out which $r$ gives the power you want rather than expanding everything.",
      "For negative or fractional $n$, first write the bracket as $(1+\\text{something})^{n}$, factoring out any constant.",
      "Then use the infinite series from the booklet, stopping at the number of terms asked for.",
      "State the validity condition: the series converges only when the 'something' has modulus less than 1.",
    ],
    watchFor: [
      "Forgetting to factor out before using the infinite form. $(2+x)^{-1}$ must become $\\frac{1}{2}(1+\\frac{x}{2})^{-1}$ first.",
      "Omitting the range of validity — it is a mark of its own, and it changes when you factor out.",
      "Raising only part of a term: in $(2x)^{3}$ the 2 is cubed as well.",
    ],
  },
  {
    paper: "pure",
    specCode: "4.2",
    idea: "A recurrence relation defines each term from the one before, so there is no shortcut to the tenth term other than climbing to it. The behaviour it produces — increasing, decreasing, periodic or converging — is usually what the question is really about.",
    method: [
      "Read the subscripts carefully: $u_{n+1}=f(u_{n})$ builds forwards from a given first term.",
      "Substitute repeatedly, one term at a time.",
      "Increasing means every term exceeds the one before; decreasing is the reverse; periodic means the values cycle.",
      "A sequence converges to a limit $L$ when $L=f(L)$, so set the two equal and solve.",
    ],
    watchFor: [
      "Treating the recurrence as an nth-term formula and substituting $n=4$ directly.",
      "Losing a minus sign partway up the ladder — one slip corrupts everything after it.",
      "A limit only exists if the sequence actually converges. Solving $L=f(L)$ finds a candidate, not a guarantee.",
    ],
  },
  {
    paper: "pure",
    specCode: "4.3",
    idea: "Sigma notation is shorthand for a sum: the letter underneath says where to start, the number on top where to stop, and the expression says what to add. Splitting it into pieces you recognise is usually the whole technique.",
    method: [
      "Write out the first two or three terms if the notation is unclear.",
      "A sum splits over addition, and constant multipliers come outside.",
      "A constant term is added once for EVERY value of the index, so it contributes (constant $\\times$ number of terms).",
      "$\\displaystyle\\sum_{r=1}^{n}r=\\frac{n(n+1)}{2}$, which is just the arithmetic series formula.",
      "To sum from a value other than 1, work out the sum from 1 and subtract the part you do not want.",
    ],
    watchFor: [
      "Adding a constant once instead of once per term.",
      "Miscounting the number of terms. From $r=3$ to $r=10$ there are 8 terms, not 7.",
      "The index letter is a dummy — it does not appear in the answer.",
    ],
  },
  {
    paper: "pure",
    specCode: "4.4",
    idea: "An arithmetic sequence adds the same amount each time. Its sum has a neat proof: pair the first term with the last, the second with the second-last, and every pair has the same total.",
    method: [
      "The nth term is $a+(n-1)d$ — note $n-1$, because the first term has had no differences added yet.",
      "The sum is $S_{n}=\\dfrac{n}{2}\\left(2a+(n-1)d\\right)$, which IS in the booklet.",
      "Equivalently $S_{n}=\\dfrac{n}{2}(a+l)$ where $l$ is the last term: the number of terms times the average of the ends.",
      "Given two terms, form two equations and solve simultaneously for $a$ and $d$.",
      "To find $n$ from a given sum, substitute and solve the resulting quadratic.",
    ],
    watchFor: [
      "Using $n$ where $(n-1)$ belongs. There are $n$ terms but only $n-1$ gaps.",
      "The nth term formula is NOT in the booklet even though the sum is.",
      "When solving for $n$, reject any negative or fractional root and say why — it is a mark.",
    ],
  },
  {
    paper: "pure",
    specCode: "4.5",
    idea: "A geometric sequence multiplies by the same amount each time. If that multiplier has modulus less than 1 the terms shrink fast enough that even an infinite number of them add to a finite total.",
    method: [
      "The nth term is $ar^{\\,n-1}$ — again $n-1$, because the first term has been multiplied zero times.",
      "The sum of $n$ terms is $S_{n}=\\dfrac{a(1-r^{n})}{1-r}$, which is given.",
      "The sum to infinity is $S_{\\infty}=\\dfrac{a}{1-r}$, valid ONLY when $|r|<1$.",
      "Find $r$ by dividing any term by the one before it.",
      "For 'how many terms until', set up an inequality and take logarithms to solve for $n$.",
    ],
    watchFor: [
      "Using the sum to infinity without checking $|r|<1$. Stating that condition is usually a mark in itself.",
      "The nth term formula is not in the booklet; the sum formulae are.",
      "Dividing by $1-r$ when $r>1$ gives a negative denominator — use the equivalent form $\\frac{a(r^{n}-1)}{r-1}$ to keep things positive.",
    ],
  },
  {
    paper: "pure",
    specCode: "4.6",
    idea: "The modelling decision is almost always the same one: does the quantity change by a fixed AMOUNT each period, or by a fixed PERCENTAGE? Fixed amount is arithmetic; fixed percentage is geometric.",
    method: [
      "Read for the words. 'Increases by £200 each year' is arithmetic; 'increases by 3% each year' is geometric.",
      "For a percentage rise of $p\\%$, the ratio is $r=1+\\dfrac{p}{100}$.",
      "Decide whether the question wants one term or a total — 'salary in year 10' is a term, 'total earned over 10 years' is a sum.",
      "Substitute into the right formula and answer in context, with units.",
      "Check the answer is plausible in size before writing it down.",
    ],
    watchFor: [
      "Confusing a term with a sum. It is the single most common error in this topic.",
      "Off-by-one on the first period: year 1 is usually the first term $a$, not $a$ plus one increase.",
      "Using $r=0.03$ instead of $1.03$ for a 3% rise.",
    ],
  },
  {
    paper: "pure",
    specCode: "6.1",
    idea: "An exponential function has the variable in the INDEX, which makes it behave quite unlike a power. For $a>1$ it grows ever faster; for $a<1$ it decays. The graph never touches the horizontal axis, because a positive number to any power stays positive.",
    method: [
      "All curves $y=a^{x}$ pass through $(0,1)$, since anything to the power zero is 1.",
      "$a>1$ rises left to right; $0<a<1$ falls.",
      "$y=e^{x}$ is the one whose gradient equals its own height everywhere.",
      "For $y=e^{ax+b}+c$, apply the transformations in order: the inside affects $x$, the outside affects $y$.",
      "The $+c$ shifts the horizontal asymptote from $y=0$ to $y=c$.",
    ],
    watchFor: [
      "The asymptote moves with a vertical translation. For $y=e^{x}-3$ it is $y=-3$, and the curve now does cross the $x$-axis.",
      "$e^{-x}$ is a reflection in the $y$-axis, not in the $x$-axis.",
      "An exponential eventually outgrows any polynomial, however large the polynomial's power.",
    ],
  },
  {
    paper: "pure",
    specCode: "6.2",
    idea: "The gradient of $e^{kx}$ is $ke^{kx}$: differentiating reproduces the function, scaled by $k$. That is precisely the property 'rate of change proportional to current size', which is why exponentials model growth and decay rather than being merely convenient for it.",
    method: [
      "Differentiate: $\\dfrac{d}{dx}\\left(e^{kx}\\right)=ke^{kx}$.",
      "For $y=Ae^{kx}$, the gradient is $Ake^{kx}$, which is $k$ times the $y$ value at every point.",
      "That means $\\dfrac{dy}{dx}=ky$, the differential equation for proportional growth.",
      "A positive $k$ gives growth and a negative $k$ decay, and $|k|$ sets how fast.",
    ],
    watchFor: [
      "Applying the power rule to $e^{kx}$. The variable is in the exponent, so the power rule does not apply at all.",
      "Dropping the $k$. Differentiating $e^{3x}$ gives $3e^{3x}$.",
      "Being able to SAY why exponentials suit these models is examinable, not just being able to differentiate them.",
    ],
  },
  {
    paper: "pure",
    specCode: "6.3",
    idea: "A logarithm answers 'what power do I need?'. $\\log_{a}x$ is the inverse of $a^{x}$, so the two undo each other — which is exactly why logarithms are the tool for getting a variable out of an exponent.",
    method: [
      "$\\log_{a}x=y$ means the same as $a^{y}=x$. Switching between these two forms solves most problems.",
      "$\\ln$ is $\\log_{e}$, the inverse of $e^{x}$.",
      "To solve $e^{ax+b}=p$, take $\\ln$ of both sides: $ax+b=\\ln p$.",
      "To solve $\\ln(ax+b)=q$, raise $e$ to both sides: $ax+b=e^{q}$.",
      "Check the answer keeps every logarithm's argument positive.",
    ],
    watchFor: [
      "You cannot take the logarithm of a negative number or of zero. Any solution making an argument non-positive must be rejected, with a reason.",
      "The graph of $\\ln x$ is the graph of $e^{x}$ reflected in $y=x$, so it has a VERTICAL asymptote at $x=0$.",
      "$\\ln(a+b)$ is not $\\ln a+\\ln b$. There is no law for the log of a sum.",
    ],
  },
  {
    paper: "pure",
    specCode: "6.6",
    idea: "If data follows $y=ax^{n}$ or $y=kb^{x}$, plotting logarithms straightens it — and the gradient and intercept of that straight line hand you the two unknown constants.",
    method: [
      "For $y=ax^{n}$: take logs to get $\\log y=\\log a+n\\log x$. Plot $\\log y$ against $\\log x$.",
      "The gradient is then $n$, and the vertical intercept is $\\log a$.",
      "For $y=kb^{x}$: $\\log y=\\log k+x\\log b$. Plot $\\log y$ against $x$ — note, against $x$ itself, not $\\log x$.",
      "Here the gradient is $\\log b$ and the intercept is $\\log k$.",
      "Undo the logarithm to recover the constant: $a=10^{\\text{intercept}}$.",
    ],
    watchFor: [
      "Reading the intercept as the constant itself. It is the LOGARITHM of the constant and must be undone.",
      "Plotting the wrong pair. A power law needs log against log; an exponential law needs log against the plain variable.",
      "Which one you have is itself a question: if log-log straightens it, it is a power law; if log against $x$ straightens it, it is exponential.",
    ],
  },
  {
    paper: "pure",
    specCode: "9.1",
    idea: "If a continuous function is negative at one point and positive at another, it must have crossed zero in between. That is the entire idea behind locating a root by change of sign.",
    method: [
      "Evaluate the function at both ends of the interval.",
      "Show the two values have opposite signs — state both values explicitly.",
      "Say the function is continuous on that interval.",
      "Conclude that there is a root between them.",
      "To tighten the interval, halve it and repeat with whichever half changes sign.",
    ],
    watchFor: [
      "Not stating continuity. A function with an asymptote can change sign with no root at all, and that is exactly the case the examiners test.",
      "Writing only 'sign change' without the two values. The numbers are the evidence.",
      "A change of sign proves at least one root, not exactly one. Two roots close together might be missed entirely.",
    ],
  },
  {
    paper: "pure",
    specCode: "9.2",
    idea: "Rearrange $f(x)=0$ into the form $x=g(x)$, then feed each output back in as the next input. If the process converges, it converges to a solution — and a staircase or cobweb diagram shows why it does or does not.",
    method: [
      "Rearrange to $x=g(x)$. There are usually several ways, and they do not all converge.",
      "Start from the given $x_{0}$ and compute $x_{1}=g(x_{0})$, then repeat.",
      "Keep full calculator accuracy between iterations and round only at the end.",
      "To show a root is correct to a given accuracy, use a change of sign over the rounding interval.",
      "Sketch $y=x$ and $y=g(x)$: staircase means the iteration approaches from one side, cobweb means it spirals in.",
    ],
    watchFor: [
      "Rounding each iterate before using it — the error compounds fast.",
      "Assuming any rearrangement works. Some diverge, and being asked which is a real question.",
      "The diagram must be drawn between the two curves, with the path shown, to earn the marks.",
    ],
  },
  {
    paper: "pure",
    specCode: "9.3",
    idea: "Newton-Raphson follows the tangent at your current guess down to the axis and uses that crossing point as the next guess. It usually converges very fast, which is why it is the method of choice — and why it fails spectacularly when the tangent is nearly horizontal.",
    method: [
      "Differentiate to get $f'(x)$. The formula itself is in the booklet.",
      "Apply $x_{n+1}=x_{n}-\\dfrac{f(x_{n})}{f'(x_{n})}$.",
      "Work out $f(x_{n})$ and $f'(x_{n})$ separately, keeping full accuracy.",
      "Repeat as many times as asked, and round only at the end.",
      "It fails when $f'(x_{n})$ is zero or near zero — the tangent is flat and throws the next guess far away.",
    ],
    watchFor: [
      "Getting $f'(x)$ wrong. The formula is given, so this is where the marks are actually lost.",
      "Rounding between iterations, which destroys the fast convergence that is the method's whole point.",
      "Being asked WHY a particular starting value fails. The answer is about the gradient there, usually a stationary point nearby.",
    ],
  },
  {
    paper: "pure",
    specCode: "9.4",
    idea: "The trapezium rule estimates an area by joining the points on the curve with straight lines instead of integrating. Whether it over- or under-estimates depends entirely on which way the curve bends.",
    method: [
      "Work out the strip width: $h=\\dfrac{b-a}{n}$, where $n$ is the number of STRIPS.",
      "Find the $y$ value at every boundary — there are $n+1$ of them.",
      "Apply $\\dfrac{h}{2}\\left[y_{0}+y_{n}+2(y_{1}+\\ldots+y_{n-1})\\right]$.",
      "The first and last count once; every interior value counts twice.",
      "For over- or under-estimate, sketch: a curve bending upwards lies below its chords, so the rule over-estimates.",
    ],
    watchFor: [
      "Confusing strips with ordinates. Five strips means six $y$ values.",
      "Doubling the end values, or failing to double the middle ones.",
      "Justifying over- or under-estimation from the curvature, not from a guess — and a sketch is the clearest justification.",
    ],
  },
  {
    paper: "pure",
    specCode: "9.5",
    idea: "In a context question the numerical method is only the engine. The marks are for setting up the right equation, choosing a sensible starting point, and saying what the answer means in the situation described.",
    method: [
      "Turn the situation into an equation of the form $f(x)=0$.",
      "Choose a starting value that makes physical sense, and say why.",
      "Apply the method, keeping full accuracy throughout.",
      "Round the final answer sensibly for the context — whole people, whole days, sensible money.",
      "Interpret: state what the number means, with units, and note any limitation of the model.",
    ],
    watchFor: [
      "Quoting eight decimal places for a quantity that is really a whole number of items.",
      "Forgetting to answer the question actually asked after doing the iteration correctly.",
      "Not checking the root is the one the context wants — an equation may have several, and only one may be physically meaningful.",
    ],
  },
  {
    paper: "pure",
    specCode: "10.1",
    idea: "A vector has both size and direction. Written in components, each direction is independent, which is what makes three dimensions no harder than one: you do the same arithmetic three times.",
    method: [
      "Column form and $\\mathbf{i},\\mathbf{j},\\mathbf{k}$ form say the same thing — convert freely between them.",
      "Add or subtract by working on each component separately.",
      "A scalar multiplies every component.",
      "$\\mathbf{i}$, $\\mathbf{j}$ and $\\mathbf{k}$ are the unit vectors along the three axes.",
      "Keep the components lined up. In column form this is automatic, which is why it is often safer.",
    ],
    watchFor: [
      "Missing out a component that happens to be zero — write $0\\mathbf{j}$ rather than leaving a gap.",
      "Applying a scalar to only the first component.",
      "A subtraction applies to every component of what is being subtracted, including its signs.",
    ],
  },
  {
    paper: "pure",
    specCode: "10.2",
    idea: "The magnitude of a vector is its length, from Pythagoras applied to the components. A unit vector is the same direction scaled to length 1, which is how you separate 'which way' from 'how far'.",
    method: [
      "Magnitude: $|\\mathbf{a}|=\\sqrt{x^{2}+y^{2}+z^{2}}$.",
      "A unit vector in the same direction is $\\dfrac{\\mathbf{a}}{|\\mathbf{a}|}$.",
      "In two dimensions, the angle with the positive $x$-axis comes from $\\tan\\theta=\\dfrac{y}{x}$.",
      "Check the quadrant from the signs of the components — the calculator will not do it for you.",
      "To build a vector from a magnitude and direction, multiply the unit vector by the magnitude.",
    ],
    watchFor: [
      "Forgetting the square root.",
      "Trusting $\\tan^{-1}$ for the direction. It returns an angle between $-90^{\\circ}$ and $90^{\\circ}$, so a vector pointing into the second or third quadrant needs adjusting.",
      "A magnitude is never negative.",
    ],
  },
  {
    paper: "pure",
    specCode: "10.3",
    idea: "Adding vectors means doing one journey then another, which is the triangle law. Multiplying by a scalar stretches without turning — so two vectors are parallel exactly when one is a scalar multiple of the other.",
    method: [
      "Add nose to tail: the resultant runs from the start of the first to the end of the last.",
      "$\\mathbf{a}-\\mathbf{b}$ is $\\mathbf{a}+(-\\mathbf{b})$, so reverse the second and then add.",
      "To test for parallel, check whether one is a scalar multiple of the other — the SAME multiple in every component.",
      "In a geometry problem, express every vector in terms of two base vectors and compare.",
      "If two routes between the same points give different expressions, they must be equal — which is how these questions are usually solved.",
    ],
    watchFor: [
      "Checking only one component for parallelism. Every component must give the same scalar.",
      "Parallel vectors can point in opposite directions — a negative scalar still counts.",
      "Getting the direction of a subtraction backwards. $\\overrightarrow{AB}=\\mathbf{b}-\\mathbf{a}$: it is the destination minus the start.",
    ],
  },
  {
    paper: "pure",
    specCode: "10.4",
    idea: "A position vector locates a point relative to the origin. The vector between two points is the difference of their position vectors, and its magnitude is the distance between them.",
    method: [
      "$\\overrightarrow{AB}=\\overrightarrow{OB}-\\overrightarrow{OA}$: second minus first.",
      "The distance $AB$ is $|\\overrightarrow{AB}|$.",
      "In three dimensions that is $\\sqrt{(\\Delta x)^{2}+(\\Delta y)^{2}+(\\Delta z)^{2}}$.",
      "The midpoint of $AB$ has position vector $\\dfrac{\\mathbf{a}+\\mathbf{b}}{2}$.",
      "For a point dividing $AB$ in a given ratio, start at $\\mathbf{a}$ and travel the right fraction of $\\overrightarrow{AB}$.",
    ],
    watchFor: [
      "Adding the position vectors instead of subtracting. That gives twice the midpoint, not the distance.",
      "The order of subtraction does not matter for a distance, because squaring removes the signs — but it does matter for a direction.",
      "Dropping the $z$ component in three dimensions.",
    ],
  },
  {
    paper: "pure",
    specCode: "10.5",
    idea: "Vector problems in context are nearly always the same shape: combine several vectors into a resultant, then take its magnitude and direction. Forces are the common case, because forces add as vectors rather than as numbers.",
    method: [
      "Write every quantity in component form.",
      "Add them component by component to get the resultant.",
      "Take the magnitude for the size, and $\\tan^{-1}$ of the ratio for the direction.",
      "For equilibrium, the resultant is zero, which gives one equation per component.",
      "Answer in context, with units, and state the direction in the form the question asked for.",
    ],
    watchFor: [
      "Adding magnitudes instead of adding vectors. Forces of 3 N and 4 N can resultant to anything from 1 N to 7 N.",
      "Equilibrium means the resultant is the ZERO VECTOR, so every component must vanish separately.",
      "Giving a direction with no reference — say what it is measured from.",
    ],
  },
  {
    paper: "pure",
    specCode: "6.4",
    idea: "The laws of logarithms are the index laws in disguise. Adding logs multiplies the arguments, subtracting divides them, and a coefficient in front becomes a power — which is what lets you collapse several logs into one and then undo it.",
    method: [
      "$\\log a+\\log b=\\log(ab)$ — adding logs multiplies.",
      "$\\log a-\\log b=\\log\\dfrac{a}{b}$ — subtracting divides.",
      "$n\\log a=\\log(a^{n})$ — a multiplier moves up into a power.",
      "To solve an equation, combine everything into a SINGLE logarithm, then undo it by raising the base to both sides.",
      "Check each solution keeps every original logarithm's argument positive.",
    ],
    watchFor: [
      "None of these laws apply to the log of a SUM. $\\log(a+b)$ cannot be split.",
      "$\\dfrac{\\log a}{\\log b}$ is not $\\log\\dfrac{a}{b}$. A quotient of logs is a change of base, not the log of a quotient.",
      "Rejecting invalid solutions is a mark, and it needs the reason stated: the argument would be negative or zero.",
    ],
  },
  {
    paper: "pure",
    specCode: "6.5",
    idea: "When the unknown is stuck in an exponent, taking logarithms of both sides is what frees it — because the power law brings the exponent down to where ordinary algebra can reach it.",
    method: [
      "Take logs of both sides. Any base works; $\\ln$ or $\\log_{10}$ are the practical choices.",
      "Apply the power law: $\\log\\left(a^{x}\\right)=x\\log a$.",
      "Rearrange to make $x$ the subject: $x=\\dfrac{\\log b}{\\log a}$.",
      "Evaluate on the calculator, keeping full accuracy until the end.",
      "If the equation is quadratic in $a^{x}$, substitute $y=a^{x}$ first, solve for $y$, then take logs.",
    ],
    watchFor: [
      "Writing $\\dfrac{\\log b}{\\log a}$ as $\\log\\dfrac{b}{a}$. These are completely different numbers.",
      "For a disguised quadratic, reject any negative value of $y$ — $a^{x}$ is always positive.",
      "Taking logs of each TERM rather than of each side. The whole side must be treated as one object.",
    ],
  },
  {
    paper: "pure",
    specCode: "6.7",
    idea: "Exponential models describe anything growing or decaying in proportion to its current size. The constants are not decoration: the coefficient is the starting amount and the sign of the exponent decides growth against decay.",
    method: [
      "In $N=Ae^{kt}$, substituting $t=0$ gives $N=A$, so $A$ is the initial value.",
      "A positive $k$ means growth; a negative $k$ means decay, and $|k|$ sets the speed.",
      "To find $N$ at a given time, substitute and evaluate, keeping full accuracy.",
      "To find WHEN a value is reached, set $N$ to that value and take logarithms.",
      "Interpret in context with units, and state the model's limitations if asked.",
    ],
    watchFor: [
      "Rounding partway through. Carry the full value in the calculator and round only at the end.",
      "A decay model approaches zero but never reaches it, so 'when does it reach zero' has no answer — which is itself a limitation worth stating.",
      "Unbounded exponential growth is unrealistic over long periods: real populations run out of food or space.",
    ],
  },
];
